@startuml
'https://plantuml.com/sequence-diagram


title US02: add and configure new Room


autonumber
participant ":CreateRoomController"
participant ":House"
participant ":RoomDTOMapper"

[o-> ":CreateRoomController" : createRoom(roomDTO)
activate ":CreateRoomController"
":CreateRoomController" -> ":House" : createRoom(name, floorNumber, area, height)
activate ":House"
":House" -> "myRoom : Room" ** : Room(name, floorNumber, area, height)
activate "myRoom : Room"
"myRoom : Room" --> ":House" : myRoom
deactivate "myRoom : Room"
":House" -> ":House" : addRoomToList
":House" --> ":CreateRoomController" : myRoom
deactivate ":House"
":CreateRoomController" -> ":RoomDTOMapper" : DomainToDTO(myRoom)
activate ":RoomDTOMapper"
":RoomDTOMapper" --> ":CreateRoomController" : myRoomDTO
deactivate ":RoomDTOMapper"
[o<-- ":CreateRoomController" : myRoomDTO
deactivate ":CreateRoomController"

@enduml