@startuml
'https://plantuml.com/sequence-diagram

title <font color=#800020>US05: Add a new device to a room</font>


autonumber

participant ":AddDeviceToRoomController"
participant ":House"
participant ":RoomDTOMapper"
participant "myRoom :Room"
participant "myDevice :Device"
participant ":DeviceDTOMapper"


[o-> ":AddDeviceToRoomController" : addDeviceToRoom(roomDTO,deviceName)
":AddDeviceToRoomController" -> ":House" : getRoomList()
activate ":House"
":AddDeviceToRoomController" <-- ":House" : listOfRooms
deactivate ":House"
":AddDeviceToRoomController" -> ":RoomDTOMapper" : roomMap_DTOAndDomain(rooms)
activate ":RoomDTOMapper"
":AddDeviceToRoomController" <-- ":RoomDTOMapper" : listOfRooms_DTOAndRooms
deactivate ":RoomDTOMapper"
":AddDeviceToRoomController" -> ":AddDeviceToRoomController" : listOfRooms_DTOAndRooms.get(roomDTO)
":AddDeviceToRoomController" -> "myRoom :Room" : createDevice(deviceName)
activate "myRoom :Room"
"myRoom :Room" -> "myDevice :Device" : Device(deviceName)
activate "myDevice :Device"
"myDevice :Device" --> "myRoom :Room" : myDevice
deactivate "myDevice :Device"
"myRoom :Room" -> "myRoom :Room" : getDevices()
":AddDeviceToRoomController" <-- "myRoom :Room" : listOfDevices
deactivate "myRoom :Room"
":AddDeviceToRoomController" -> ":DeviceDTOMapper" : listOfDevices
activate ":DeviceDTOMapper"
":AddDeviceToRoomController" <-- ":DeviceDTOMapper" : listOfDevicesDTO
deactivate ":DeviceDTOMapper"
[o<-- ":AddDeviceToRoomController" : listOfDevicesDTO
deactivate ":AddDeviceToRoomController"




@enduml