@startuml
'https://plantuml.com/sequence-diagram

!theme mars
skinparam sequenceMessageAlign direction

title US08 : I want to deactivate a device, so that it is no longer used.
[o-> ":US08DeactivateDeviceController" ++ : 1 : deactivateDevice(deviceDTO)
":US08DeactivateDeviceController"-> "RoomDTOMapper" ++ : 1.1 : deviceDTOToDomain(deviceDTO)
"RoomDTOMapper"-> ":US08DeactivateDeviceController" : myDevice
":US08DeactivateDeviceController" -> "myDevice: Device" ++: 1.4: deactivateDevice(myDevice)
    "myDevice: Device" --> ":US08DeactivateDeviceController" --: true;
[o<-- ":US08DeactivateDeviceController" --: true;
@enduml